SECRET_KEY = 'iDsYGvBaLKloviKNkwMveAELMGG64L9j'
# EMAIL_HOST_PASSWORD = config['SMG_GMAIL_PASSWORD']
# AWS_ACCESS_KEY_ID = config['AWS_ACCESS_KEY_ID']
# AWS_SECRET_ACCESS_KEY = config['AWS_SECRET_ACCESS_KEY']
