# Generated by Django 3.0.7 on 2020-11-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='url_extension',
            new_name='slug',
        ),
    ]
