# Generated by Django 3.0.7 on 2020-11-12 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20201111_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student name')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Song')),
            ],
        ),
    ]
