# Generated by Django 3.1.4 on 2020-12-29 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20201228_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='gallery.gallery'),
        ),
        migrations.AlterField(
            model_name='songgroup',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_groups', to='gallery.gallery'),
        ),
    ]
