# Generated by Django 3.0.7 on 2020-11-12 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_studentname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='student_name',
        ),
    ]
