# Generated by Django 3.1.4 on 2020-12-29 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20201229_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='isCached',
            new_name='is_cached',
        ),
    ]
