# Generated by Django 3.2 on 2021-04-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_song_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='songgroup',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
