# Generated by Django 3.2 on 2021-05-14 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0011_auto_20210502_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='student_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Student Name'),
        ),
    ]
