# Generated by Django 3.0.7 on 2020-11-08 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('url_extension', models.CharField(blank=True, default='unassigned', max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='SongGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher_admin.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songId', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Song ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('isCached', models.BooleanField(default=False)),
                ('json', django_mysql.models.JSONField(default=dict)),
                ('midi', models.BinaryField()),
                ('galleries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_admin.Gallery')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_admin.SongGroup')),
            ],
        ),
    ]
