# Generated by Django 3.0.7 on 2020-11-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='galleries',
            new_name='gallery',
        ),
    ]
