# Generated by Django 3.0.7 on 2020-09-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0002_auto_20200528_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='url_extension',
            field=models.CharField(blank=True, default='unassigned', max_length=100, primary_key=True, serialize=False),
        ),
    ]
