# Generated by Django 3.0.7 on 2020-11-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0002_auto_20201108_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='song',
            name='group',
        ),
        migrations.AddField(
            model_name='song',
            name='galleries',
            field=models.ManyToManyField(to='teacher_admin.Gallery'),
        ),
        migrations.AddField(
            model_name='song',
            name='groups',
            field=models.ManyToManyField(to='teacher_admin.SongGroup'),
        ),
    ]
