# Generated by Django 3.0.7 on 2020-11-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0003_auto_20201108_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='url_extension',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
