# Generated by Django 3.0.7 on 2020-09-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0003_auto_20200927_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='work_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
