# Generated by Django 3.0.7 on 2020-11-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0004_auto_20201108_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songgroup',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_admin.Gallery'),
        ),
    ]
