# Generated by Django 3.0.7 on 2020-12-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_ip', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Last IP',
            },
        ),
    ]
