# Generated by Django 3.2 on 2021-04-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_gallery_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="order",
            field=models.IntegerField(null=True),
        ),
    ]
