# Generated by Django 3.2.4 on 2021-07-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0013_alter_song_student_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="is_editable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gallery",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
