# Generated by Django 3.0.6 on 2020-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='id',
        ),
        migrations.AddField(
            model_name='gallery',
            name='url_extension',
            field=models.CharField(blank=True, default='err', max_length=100, primary_key=True, serialize=False),
        ),
    ]
