# Generated by Django 3.0.6 on 2020-05-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='needs_screenshot',
            field=models.BooleanField(default=False),
        ),
    ]
