# Generated by Django 3.0.6 on 2020-05-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0003_auto_20200522_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(default='no description'),
        ),
    ]
