# Generated by Django 3.0.7 on 2020-12-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0003_auto_20200927_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
