# Generated by Django 3.0.6 on 2020-05-22 17:10

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0005_auto_20200522_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='api_obj',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
