# Generated by Django 3.0.6 on 2020-05-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0008_auto_20200522_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
    ]
