# Generated by Django 3.0.6 on 2020-05-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0010_remove_gallery_api_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='url_extension',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
