# Generated by Django 3.0.6 on 2020-05-22 17:18

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_admin', '0011_auto_20200522_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='api_obj',
            field=django_mysql.models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='url_extension',
            field=models.CharField(blank=True, default='err', max_length=100, primary_key=True, serialize=False),
        ),
    ]
