/**
 * Note that form some tests, this should somewhat match the data from
 * ./actions.js
 */

export const apiResponse = {
  title: "Test Gallery",
  description: "description",
  pk: 2,
  slug: "test-gallery",
  songData: [
    [
      {
        metadata: {
          bars: 4,
          beats: 4,
          instrument: "marimba",
          octaves: 2,
          percussion: "electronic",
          percussionNotes: 2,
          rootNote: 48,
          rootOctave: 4,
          rootPitch: 0,
          scale: "major",
          subdivision: 2,
          tempo: 120,
        },
        midiBytes:
          "TVRoZAAAAAYAAQACA8BNVHJrAAAACwD/UQMHoSAA/y8ATVRyawAAAHIAwQ2lQJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINgkT5/AIE+AINggT4AAJE+fwCRPH8AkTt/g2CBPgAAgTwAAIE7AACRN38AkTl/g2CBNwAAgTkAsGD/LwA=",
        name: "Mark J.",
        songId: "5676759593254912",
      },
      {
        metadata: {
          bars: 4,
          beats: 4,
          instrument: "marimba",
          octaves: 2,
          percussion: "electronic",
          percussionNotes: 2,
          rootNote: 48,
          rootOctave: 4,
          rootPitch: 0,
          scale: "major",
          subdivision: 2,
          tempo: 120,
        },
        midiBytes:
          "TVRoZAAAAAYAAQACA8BNVHJrAAAACwD/UQMHoSAA/y8ATVRyawAAAHIAwQ2lQJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINgkT5/AIE+AINggT4AAJE+fwCRPH8AkTt/g2CBPgAAgTwAAIE7AACRN38AkTl/g2CBNwAAgTkAsGD/LwA=",
        name: "Mark J.",
        songId: "5676759593254912",
      },
      {
        metadata: {
          bars: 4,
          beats: 4,
          instrument: "marimba",
          octaves: 2,
          percussion: "electronic",
          percussionNotes: 2,
          rootNote: 48,
          rootOctave: 4,
          rootPitch: 0,
          scale: "major",
          subdivision: 2,
          tempo: 120,
        },
        midiBytes:
          "TVRoZAAAAAYAAQACA8BNVHJrAAAACwD/UQMHoSAA/y8ATVRyawAAAHIAwQ2lQJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINgkT5/AIE+AINggT4AAJE+fwCRPH8AkTt/g2CBPgAAgTwAAIE7AACRN38AkTl/g2CBNwAAgTkAsGD/LwA=",
        name: "Mark J.",
        songId: "5676759593254912",
      },
      {
        metadata: {
          bars: 4,
          beats: 4,
          instrument: "marimba",
          octaves: 2,
          percussion: "electronic",
          percussionNotes: 2,
          rootNote: 48,
          rootOctave: 4,
          rootPitch: 0,
          scale: "major",
          subdivision: 2,
          tempo: 120,
        },
        midiBytes:
          "TVRoZAAAAAYAAQACA8BNVHJrAAAACwD/UQMHoSAA/y8ATVRyawAAAHIAwQ2lQJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINgkT5/AIE+AINggT4AAJE+fwCRPH8AkTt/g2CBPgAAgTwAAIE7AACRN38AkTl/g2CBNwAAgTkAsGD/LwA=",
        name: "Mark J.",
        songId: "5676759593254912",
      },
      "A Group of Marks",
    ],
    [
      {
        metadata: {
          bars: 4,
          beats: 4,
          instrument: "marimba",
          octaves: 2,
          percussion: "electronic",
          percussionNotes: 2,
          rootNote: 48,
          rootOctave: 4,
          rootPitch: 0,
          scale: "major",
          subdivision: 2,
          tempo: 120,
        },
        midiBytes:
          "TVRoZAAAAAYAAQACA8BNVHJrAAAACwD/UQMHoSAA/y8ATVRyawAAAHIAwQ2lQJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINgkT5/AIE+AINggT4AAJE+fwCRPH8AkTt/g2CBPgAAgTwAAIE7AACRN38AkTl/g2CBNwAAgTkAsGD/LwA=",
        name: "Lilly G.",
        songId: "5676759593254912",
      },
      {
        metadata: {
          bars: 4,
          beats: 4,
          instrument: "marimba",
          octaves: 2,
          percussion: "electronic",
          percussionNotes: 2,
          rootNote: 48,
          rootOctave: 4,
          rootPitch: 0,
          scale: "major",
          subdivision: 2,
          tempo: 120,
        },
        midiBytes:
          "TVRoZAAAAAYAAQACA8BNVHJrAAAACwD/UQMHoSAA/y8ATVRyawAAAHIAwQ2lQJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINgkT5/AIE+AINggT4AAJE+fwCRPH8AkTt/g2CBPgAAgTwAAIE7AACRN38AkTl/g2CBNwAAgTkAsGD/LwA=",
        name: "Lilly G.",
        songId: "5676759593254912",
      },
      {
        metadata: {
          bars: 4,
          beats: 4,
          instrument: "marimba",
          octaves: 2,
          percussion: "electronic",
          percussionNotes: 2,
          rootNote: 48,
          rootOctave: 4,
          rootPitch: 0,
          scale: "major",
          subdivision: 2,
          tempo: 120,
        },
        midiBytes:
          "TVRoZAAAAAYAAQACA8BNVHJrAAAACwD/UQMHoSAA/y8ATVRyawAAAHIAwQ2lQJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINgkT5/AIE+AINggT4AAJE+fwCRPH8AkTt/g2CBPgAAgTwAAIE7AACRN38AkTl/g2CBNwAAgTkAsGD/LwA=",
        name: "Lilly G.",
        songId: "5676759593254912",
      },
      {
        metadata: {
          bars: 4,
          beats: 4,
          instrument: "marimba",
          octaves: 2,
          percussion: "electronic",
          percussionNotes: 2,
          rootNote: 48,
          rootOctave: 4,
          rootPitch: 0,
          scale: "major",
          subdivision: 2,
          tempo: 120,
        },
        midiBytes:
          "TVRoZAAAAAYAAQACA8BNVHJrAAAACwD/UQMHoSAA/y8ATVRyawAAAHIAwQ2lQJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINggT4AAJE+f4NgkT5/AIE+AINgkT5/AIE+AINggT4AAJE+fwCRPH8AkTt/g2CBPgAAgTwAAIE7AACRN38AkTl/g2CBNwAAgTkAsGD/LwA=",
        name: "Lilly G.",
        songId: "5676759593254912",
      },
      "A Group of Lillys",
    ],
  ],
};
