# Generated by Django 3.0.6 on 2020-05-22 02:59

from django.db import migrations, models
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200521_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='id',
        ),
        migrations.AddField(
            model_name='gallery',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('e295beed-5538-4d54-93f0-91213161e784'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='api_obj',
            field=django_mysql.models.JSONField(default=list),
        ),
    ]
