# Generated by Django 3.0.6 on 2020-06-02 23:46

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_extension', models.CharField(max_length=100)),
                ('api_obj', django_mysql.models.JSONField(default=list)),
            ],
        ),
    ]
