# Generated by Django 3.0.6 on 2020-06-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_done'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Done',
        ),
    ]
